# Generated by Django 2.2 on 2019-04-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
