# Generated by Django 2.2 on 2019-04-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20190422_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='price',
            new_name='count',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('num', 'Number'), ('rad', 'Radio')], max_length=1),
        ),
    ]
