# Generated by Django 2.2 on 2019-04-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20190422_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('num', 'Number'), ('rad', 'Radio')], max_length=3),
        ),
    ]
